title: Making ML Intelligible
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

plugins:
  - jekyll-feed           # RSS feed for blog
  - jekyll-paginate       # Paginate the list of blog posts
# - jekyll-seo-tag

# Blogging setup
paginate: 5               # Number of posts to display at any one time

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  # - name: Concepts
  #   link: 'concepts/'
  - name: Resources
    link: 'resources/'
  - name: Makers All
    link: 'https://makersall.org/'

  # - name: Blog
  #   link: 'blog/'
